apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'worasit.dmk501@gmail.com'
    privateKeySecretRef:
      name: letencrypt-prod
    http01: {}

