#!/usr/bin/env bash
REPO_NAME="worasit/kubernetes-prod-example"
travis encrypt-file service-account.json -r ${REPO_NAME}
# travis will generate the file 'service-account.json.enc'
# copy the command generated by travis CLI and paste to the before_install step